--- 
title: "Learn Maths With Alice"
author: "Lingyun Zhang"
date: "2019-01-05"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
links-as-notes: true
colorlinks: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preface {-}

Like other parents, I want to help my children (Alan and Alice) learn maths well. Fortunately, I qualify for this job---I was good at maths when I was a student and I earned a PhD in Mathematical Statistics at age 30. To help my children, especially Alice, I prepare the learning materials, and these materials form the current book.

This book covers Year 1 to Year 13 school maths. There are three main parts. Part I is about Arithmetic. Part II comprises Algebra, Geometry (including Coordinate Geometry) and Trigonometric. Part III contains Elementary Calculus.

For sure, this book is useful for my tasks helping my children, and I hope it will also be useful for you as parents helping your children learn maths. So, the intended audience of this book are those parents and their children.

# Introduction {-}

# Part I: Arithmetic {-}

## Integers

# Part II: Algebra, Geometry and Trigonometric {-}

## Solving equations with two unknowns

Let's try to solve the this problem: 

**Alan thought two numbers and he asked Alice to guess what they are. Alan told Alice that the sum of the two numbers is 100 and the difference between the two numbers is 36. Can you help Alice figure out the two numbers?**

**Analysis:** We must find the two numbers, which are *unknowns* to us. So, why not let the two unknowns be $x$ and $y$. Immediately, we have the following two **equations** 
$$
\left\{
\begin{array}{ccl}
x + y &=& 100\\
x - y &=& 36
\end{array}
\right.
$$
Now, if we can solve the two equations then we solve the problem.

This chapter is about solving equations with two unknowns. By that, I mean we want to find $x$ and $y$ in equations like the above one. The method for solving this type of equations is called the *elimination method*; as the name indicates the key is that we firstly **knock out one unknown** and then we can get the other one.

For the above the problem, we can knock out $y$ be adding the two equations together
$$
2x = 136,
$$
from which easily we have $x=136/2=68$. Next, to find $y$, we can either replace 68 for $x$ in one equation to have $68+y=100$, which yields $y=32$, or this time we knock out $y$ by using the top equation to subtract the second equation
$$
2y = 64,
$$
from which again we get $y=32$.

Let's have another problem.

**Solve the following equations:**
\begin{align}
2x + 3y & =  6 (\#eq:ex2-1)\\
x + y & =  2 (\#eq:ex2-2)
\end{align}

**Solution:** We can use the elimination method. In order to knock out $x$, we multiply 2 on both sides of Eq. \@ref(eq:ex2-2), and we have
\begin{equation}
2x + 2y = 4 (\#eq:ex2-3)
\end{equation}
The result of Eq. \@ref(eq:ex2-1) minus Eq. \@ref(eq:ex2-3) is
$$
y=2.
$$
Plugging $y=2$ into \@ref(eq:ex2-2). we have 
$$
x + 2 = 2,
$$
from which we get $x=0$. Final answer: $x=0$ and $y=2.$

Our third problem:
**Solve the following equations**
\begin{align}
y &= \frac{x}{2} (\#eq:ex3-1)\\
x + 3y &= 10 (\#eq:ex3-2)
\end{align}


We provide two solutions for this problem. The essential spirits in the two solutions are the same---**we must firstly eliminate one unknown in order to get the other unknown.**

**Solution 1:** Since Eq. \@ref(eq:ex3-1) says $y$ is $x/2$, we can replace $y$ by $x/2$ in Eq. \@ref(eq:ex3-2) and we have
$$
x + 3\times \frac{1}{2}\times x = 10,
$$
which can be simplified to
\begin{equation}
\frac{5}{2}x = 10 (\#eq:ex3-3)
\end{equation}
Multiplying $2/5$ on both sides of \@ref(eq:ex3-3) yields $x=4$. $y=x/2=4/2=2$. Final answer: $x=4$ and $y=2$.

**Solution 2:** We firstly change \@ref(eq:ex3-1) to 
\begin{equation}
\frac{1}{2}x - y = 0 (\#eq:ex3-4)
\end{equation}
Eq. \@ref(eq:ex3-4)$\times 3$ + \@ref(eq:ex3-2) is
$$
\frac{5}{2}x = 10,
$$
from which we have $x=4$. $y=x/2=4/2=2$. Final answer: $x=4$ and $y=2$.

Our last problem is more "general" and a little bit more challenging (at least to Alice).

**Solve the equations.**
\begin{align}
3y - 6 + 7x & = 0 (\#eq:ex4-1)\\
4x & = 2y + 5 (\#eq:ex4-2)
\end{align}

**Solution.** Firstly, we **re-arrange** (or **rewrite**) Eq. \@ref(eq:ex4-1) and Eq. \@ref(eq:ex4-2) as 
\begin{align}
7x+3y & = 6 (\#eq:ex4-3)\\
4x -2y & = 5 (\#eq:ex4-4)
\end{align}
Next step, suppose we want to knock out $x$ in the above two equations, how do we do it?
Here is the trick: We multiply 4 on both sides of Eq. \@ref(eq:ex4-3) and multiply 7 on both sides of Eq. \@ref(eq:ex4-4) to have
\begin{align}
28x+12y & = 24 (\#eq:ex4-5)\\
28x -14y & =35 (\#eq:ex4-6)
\end{align}
Eq. \@ref(eq:ex4-5) minus Eq. \@ref(eq:ex4-6) results in
$$
26y = -11,
$$
from which we get $y=-11/26$. To find $x$, we must knock out $y$---we multiply 2 on both sides of Eq. \@ref(eq:ex4-3) and we multiply 3 on both sides of Eq. \@ref(eq:ex4-4) to have
\begin{align}
14x + 6y & = 12 (\#eq:ex4-7)\\
12x - 6y & = 15 (\#eq:ex4-8);
\end{align}
adding Eq. \@ref(eq:ex4-7) and Eq. \@ref(eq:ex4-8), we have
$$
26x = 27,
$$
which is to say $x=27/26$. Final answer: $x=27/26$ and $y=-11/26$.

# Part III: Elementary Calculus {-}
